# Site settings
title: NBi - Testing framework for Microsoft Business Intelligence platform
email: cedric.charlier@yucom.be
description: > # this means to ignore newlines until "baseurl:"
  NBi is a testing framework (add-on to NUnit) for Microsoft Business Intelligence platform and Data Access.
  The main goal of this framework is to let users create tests with a declarative approach based on an Xml syntax.
  By the means of NBi, you don't need to develop C# code to specify your tests!
  Either, you don't need Visual Studio to compile your test suite.
  Just create an Xml file and let the framework interpret it and play your tests.
  The framework is designed as an add-on of NUnit but with the possibility to port it easily to other testing frameworks.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.nbi.io" # the base hostname & protocol for your site
twitter_username: Seddryck
github_username:  Seddryck
repository: https://github.com/Seddryck/NBi
google_analytics_id: "UA-64208458-1" # https://www.google.com/analytics/


# Build settings
markdown: kramdown
highlighter: rouge
exclude: ['README.md', 'Gemfile', 'Gemfile.lock']

# Collections
collections:
  documentation:
    output: true
  download:
    output: true
  automation:
    output: true
