- title: Getting started
  docs:
  - home

- title: Genbi
  docs:
  - generate-tests
  - condition-template
  - source-test-cases-from-query

- title: genbiL: macro language
  docs:
  - genbil
  - cases-load
