- title: Getting started
  docs:
  - home

- title: Genbi
  docs:
  - generate-tests
  - condition-template
  - source-test-cases-from-query

- title: genbiL - macro language
  docs:
  - genbil
  - comments

- title: Test-cases management
  docs:
  - cases-load
  - cases-save
  - cases-scope
  - cases-copy
  - cases-merge
  - cases-cross

- title: Columns of test-cases
  docs:
  - column-add
  - column-remove
  - column-hold
  - column-rename
  - column-move
  - column-replace
  - column-substitute
  - column-concatenate

- title: Rows of test-cases
  docs:
  - rows-filter
  - rows-distinct

- title: Test template
  docs:
  - template-load

- title: Settings management
  docs:
  - settings-load

- title: Test-suite management
  docs:
  - suite-generate
  - suite-save
  - suite-include
